### ISSUE TITLE
USER STORY:As a user I can view each post on its own page so that I can read and interact with them

### ISSUE THREAD

**Issue by dylankane** [dylankane/pedal#10]
EPIC: Post board

As a **user** I can **view each post on its own page** so that **I can read and interact with all the information**

**Acceptance Criteria**

- [x] Post view should show all images uploaded with post
- [x] Contain all the information of the post
- [x] Be laid out in a clear and readable way

**Tasks**

- [x] Create the view
- [x] Create a template to render the view
- [x] Connect URLs
