### ISSUE TITLE
USER STORY: As a user I can view all other posts on one main page so that I can see a brief outline of each post

### ISSUE THREAD

**Issue by dylankane** [dylankane/pedal#9]
EPIC: Blog Post Section

As a **user** I can **view all other posts on one main page** so that **I can see a brief outline of each post**

**Acceptance Criteria**

- [x]  Post area or board should be the home/landing page of the site
- [x]  It should display all the posts created by users
- [x]  It should have the posts displayed by the last created at the beginning

**Tasks** 

- [x] Create the view
- [x]  Create a template to render the view
- [x]  Connect URLs
